apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
  labels:
    app: deploy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-api
  template:
    metadata:
      labels:
        app: deploy-api
    spec:
      serviceAccountName: deploy-api-serviceaccount # Add this line
      containers:
        - name: deploy-api
          image: deploy-api:latest # <-- your local build
          imagePullPolicy: Never # <-- IMPORTANT so Kube doesn’t try to pull from DockerHub
          ports:
            - containerPort: 3000
          env:
            - name: PAT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-pat-secret
                  key: token
            - name: API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: api-tokens-secret
                  key: tokens

---
# Service (updated to ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: deploy-api-service
spec:
  type: ClusterIP
  selector:
    app: deploy-api
  ports:
    - port: 3000
      targetPort: 3000
