apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Pods permissions
  - apiGroups: [""] # core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
